services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER:-usuario_sprint}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password_segura}
      POSTGRES_DB: ${DB_NAME:-sprint_db}
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: django_web
    working_dir: /app
    command: >
      bash -c "pip install --upgrade pip && 
      pip install -r requirements.txt && 
      python manage.py makemigrations && 
      python manage.py migrate && 
      python manage.py seed_techniques &&
      python manage.py seed_user &&
      python manage.py seed_demo_users && 
      python manage.py setup_langgraph && 
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data: